# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot

# Mod properties
mod_id = furnacedistributor
mod_name = Furnace Distributor
mod_version = 1.0.0
maven_group = com.thonyy.furnacedistributor
archives_name = furnacedistributor
enabled_platforms = fabric,neoforge

mod_description = Distribute and collect items across multiple furnaces quickly and easily.
mod_authors = Thonyy
mod_license = MIT

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version=13.0.8

fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1

neoforge_version=21.1.251
