modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
#logoFile = ""

[[mixins]]
config = "furnacedistributor.mixins.json"

[features.${mod_id}]
javaVersion = "[21,)"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},14)"
ordering = "AFTER"
side = "BOTH"
